version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - ci
    commit-message:
      prefix: ci
    reviewers:
      - EgorHenek
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    reviewers:
      - EgorHenek
    commit-message:
      prefix: build
