name: Conventional commits
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  cog_check_job:
    runs-on: ubuntu-latest
    name: Check conventional commit compliance
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Conventional commits check
        uses: oknozor/cocogitto-action@v3
        with:
          check-latest-tag-only: true
